### ISSUE TITLE
auro-alerts: UI attribute is not reflected within the element in Svelte 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-alerts#14]
## Describe the bug

In some frameworks, there appears to be an issue where the technique of using an attribute selector to theme a custom element is not reflected within the scope of the rendered element. 

This issue and image are from @geoffrich 

![87ba077c-11c3-4d15-9978-a95cd956157f](https://user-images.githubusercontent.com/181089/115121215-48b16d00-9f66-11eb-94db-67e2a49e5217.jpg)

## Expected behavior

The element should have the correct UI when used in Svelte.

## Correction suggestion 

The suggestion to address this issue is to add the following to all the defined properties within the scope of the element. 

```js
myProp: {reflect: true}
```

**Comment by geoffrich** [comment]
Note that you only need to reflect properties where the attribute is used for styling. I think this is all of them in the auro-alerts case, but that might not be true with other elements.

**Comment by blackfalcon** [comment]
> Note that you only need to reflect properties where the attribute is used for styling. I think this is all of them in the auro-alerts case, but that might not be true with other elements.

The issue is... when a style attribute is used for BOTH a Property within the scope of the element AND a styled attribute. E.g. 

```js
  static get properties() {
    return {
      error:          { type: Boolean },
    };
  }
```

```scss
:host([error]) {
  .alert {
    border-color: var(--auro-color-alert-error-on-light);
  }

  svg {
    color: var(--auro-color-alert-error-on-light);
  }
}
```

If the styled attribute is only for a CSS hook, then this is not needed. E.g. auro-loader

@gusnaughton reported an issue with auro-loader related to this. @gusnaughton can you elaborate as to the issue and how it was resolved?

**Comment by geoffrich** [comment]
Right... I always forget about the standalone attribute case.

You can see my PR for the auro-loader fix: https://github.com/AlaskaAirlines/auro-loader/pull/6. There were two issues
- properties that corresponded to styling attributes needed to be reflected
- there were internal properties corresponding to standalone attributes (sm and md). I renamed them to avoid a conflict with the attribute names.
