### ISSUE TITLE
auro-alerts: properties need default values

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-alerts#16]
## Describe the bug
The following properties don't have default values:
- error
- success
- warning
- information

This prevents Svelte apps from using the boolean attribute shorthand, e.g. `<auro-alerts error>`.

## Expected behavior
The above properties default to false.

**Comment by blackfalcon** [comment]
This issue is negated. Boolean values will be replaced with enumerated attributes https://github.com/AlaskaAirlines/auro-alerts/issues/17 per https://auro.alaskaair.com/getting-started/developers/generator/define-api
