### ISSUE TITLE
auro-alerts: conditional CSS

### ISSUE THREAD

**Issue by ecommerceUXdesign** [AlaskaAirlines/auro-alerts#7]
# General Support Request
The current feature of `fixed` supports additional code for fixed pixel sizes. Efforts were put towards making the loading of this CSS conditional. 

https://stackblitz.com/edit/j9k3ga?file=my-element.js

But there is an issue with this WC that the condition is not working as expected. Further research is needed. 

See https://github.com/AlaskaAirlines/auro-alerts/pull/6 for reference.

**Comment by blackfalcon** [comment]
That has proved to be a non-issue that doesn't need to be solved.
